"""Init

Revision ID: e7b4b216cd72
Revises: 38d18116ed57
Create Date: 2023-11-20 23:36:28.458053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7b4b216cd72'
down_revision: Union[str, None] = '38d18116ed57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('photos', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_photos_description', table_name='photos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_photos_description', 'photos', ['description'], unique=False)
    op.alter_column('photos', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
